In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing (pd.read_csv)
from sklearn.preprocessing import LabelEncoder #import label encoder
from sklearn.model_selection import train_test_split #dataset splitting before fitting model
from sklearn.neighbors import KNeighborsRegressor #K-Neigbors Regression Model,
from sklearn.metrics import confusion_matrix #Metrics for Evaluation the prediction
from sklearn.metrics import accuracy_score #Metrics for Evaluation the prediction
from sklearn.metrics import classification_report #Precision, Recall

In [2]:
train = pd.read_csv("processed.cleveland.data")

In [3]:
train.head()

63.0  1.0  1.0.1  145.0  233.0  1.0.2  2.0  150.0  0.0  2.3  3.0 0.0.1  \
0  67.0  1.0    4.0  160.0  286.0    0.0  2.0  108.0  1.0  1.5  2.0   3.0   
1  67.0  1.0    4.0  120.0  229.0    0.0  2.0  129.0  1.0  2.6  2.0   2.0   
2  37.0  1.0    3.0  130.0  250.0    0.0  0.0  187.0  0.0  3.5  3.0   0.0   
3  41.0  0.0    2.0  130.0  204.0    0.0  2.0  172.0  0.0  1.4  1.0   0.0   
4  56.0  1.0    2.0  120.0  236.0    0.0  0.0  178.0  0.0  0.8  1.0   0.0   

   6.0  0  
0  3.0  2  
1  7.0  1  
2  3.0  0  
3  3.0  0  
4  3.0  0

In [4]:
title = LabelEncoder()
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 14 columns):
63.0     302 non-null float64
1.0      302 non-null float64
1.0.1    302 non-null float64
145.0    302 non-null float64
233.0    302 non-null float64
1.0.2    302 non-null float64
2.0      302 non-null float64
150.0    302 non-null float64
0.0      302 non-null float64
2.3      302 non-null float64
3.0      302 non-null float64
0.0.1    302 non-null object
6.0      302 non-null object
0        302 non-null int64
dtypes: float64(11), int64(1), object(2)
memory usage: 33.1+ KB


In [5]:
#Float to Int conversion
train['63.0'] = train['63.0'].astype(int)
train['1.0'] = train['1.0'].astype(int)
train['1.0.1'] = train['1.0.1'].astype(int)
train['145.0'] = train['145.0'].astype(int)
train['233.0'] = train['233.0'].astype(int)
train['1.0.2'] = train['1.0.2'].astype(int)
train['2.0'] = train['2.0'].astype(int)
train['150.0'] = train['150.0'].astype(int)
train['0.0'] = train['0.0'].astype(int)
train['2.3'] = train['2.3'].astype(int)
train['3.0'] = train['3.0'].astype(int)

In [6]:
train.loc[train['0.0.1'] == "?"]

63.0  1.0  1.0.1  145.0  233.0  1.0.2  2.0  150.0  0.0  2.3  3.0 0.0.1  \
165    52    1      3    138    223      0    0    169    0    0    1     ?   
191    43    1      4    132    247      1    2    143    1    0    2     ?   
286    58    1      2    125    220      0    0    144    0    0    2     ?   
301    38    1      3    138    175      0    0    173    0    0    1     ?   

     6.0  0  
165  3.0  0  
191  7.0  1  
286  7.0  0  
301  3.0  0

In [7]:
train.iloc[165,11]=0
train.iloc[191,11]=0
train.iloc[286,11]=0
train.iloc[301,11]=0

In [8]:
train.loc[train['0.0.1'] == "?"]

Empty DataFrame
Columns: [63.0, 1.0, 1.0.1, 145.0, 233.0, 1.0.2, 2.0, 150.0, 0.0, 2.3, 3.0, 0.0.1, 6.0, 0]
Index: []

In [9]:
train.loc[train['6.0'] == "?"]

63.0  1.0  1.0.1  145.0  233.0  1.0.2  2.0  150.0  0.0  2.3  3.0 0.0.1  \
86     53    0      3    128    216      0    2    115    0    0    1   0.0   
265    52    1      4    128    204      1    0    156    1    1    2   0.0   

    6.0  0  
86    ?  0  
265   ?  2

In [10]:
train.iloc[86,12]=0
train.iloc[265,12]=0

In [11]:
train.loc[train['6.0'] == "?"]

Empty DataFrame
Columns: [63.0, 1.0, 1.0.1, 145.0, 233.0, 1.0.2, 2.0, 150.0, 0.0, 2.3, 3.0, 0.0.1, 6.0, 0]
Index: []

In [12]:
train['0.0.1'] = train['0.0.1'].astype(float).astype(int)
train['6.0'] = train['6.0'].astype(float).astype(int)

In [13]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 14 columns):
63.0     302 non-null int64
1.0      302 non-null int64
1.0.1    302 non-null int64
145.0    302 non-null int64
233.0    302 non-null int64
1.0.2    302 non-null int64
2.0      302 non-null int64
150.0    302 non-null int64
0.0      302 non-null int64
2.3      302 non-null int64
3.0      302 non-null int64
0.0.1    302 non-null int64
6.0      302 non-null int64
0        302 non-null int64
dtypes: int64(14)
memory usage: 33.1 KB


In [14]:
#Checking any missing values
NAs = pd.concat([train.isnull().sum()], axis=1, keys=["Train"])
NAs[NAs.sum(axis=1) > 0]

Empty DataFrame
Columns: [Train]
Index: []

In [15]:
X = train.drop(['0'], axis = 1) #input feature
y = train['0'].values #target

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

In [17]:
model1 = KNeighborsRegressor(n_neighbors=1)
model2 = KNeighborsRegressor(n_neighbors=3)
model3 = KNeighborsRegressor(n_neighbors=5)
model4 = KNeighborsRegressor(n_neighbors=7)
model5 = KNeighborsRegressor(n_neighbors=9)

In [18]:
model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)
model4.fit(X_train, y_train)
model5.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=None, n_neighbors=9, p=2,
          weights='uniform')

In [19]:
prediction1 = model1.predict(X_test)
prediction2 = model2.predict(X_test)
prediction3 = model3.predict(X_test)
prediction4 = model4.predict(X_test)
prediction5 = model5.predict(X_test)

In [20]:
conf1 = confusion_matrix(y_test, prediction1.round())
print(conf1)

[[10  3  2  0  0]
 [ 3  1  1  0  0]
 [ 0  1  0  3  0]
 [ 3  2  0  0  0]
 [ 1  1  0  0  0]]


In [21]:
conf2 = confusion_matrix(y_test, prediction2.round())
print(conf2)

[[7 8 0 0 0]
 [0 4 0 1 0]
 [0 1 2 1 0]
 [3 0 2 0 0]
 [0 1 1 0 0]]


In [22]:
conf3 = confusion_matrix(y_test, prediction3.round())
print(conf3)

[[7 7 1 0 0]
 [1 3 1 0 0]
 [0 2 1 1 0]
 [0 3 2 0 0]
 [0 1 1 0 0]]


In [23]:
conf4 = confusion_matrix(y_test, prediction4.round())
print(conf4)

[[9 6 0 0 0]
 [1 3 1 0 0]
 [0 3 1 0 0]
 [1 2 2 0 0]
 [0 1 1 0 0]]


In [24]:
conf5 = confusion_matrix(y_test, prediction5.round())
print(conf5)

[[10  5  0  0  0]
 [ 1  3  1  0  0]
 [ 0  1  3  0  0]
 [ 1  2  2  0  0]
 [ 0  1  1  0  0]]


In [25]:
print ('Accuracy 1 :',accuracy_score(y_test, prediction1.round()))
print ('Accuracy 2 :',accuracy_score(y_test, prediction2.round()))
print ('Accuracy 3 :',accuracy_score(y_test, prediction3.round()))
print ('Accuracy 4 :',accuracy_score(y_test, prediction4.round()))
print ('Accuracy 5 :',accuracy_score(y_test, prediction5.round()))

Accuracy 1 : 0.3548387096774194
Accuracy 2 : 0.41935483870967744
Accuracy 3 : 0.3548387096774194
Accuracy 4 : 0.41935483870967744
Accuracy 5 : 0.5161290322580645


In [26]:
print (classification_report(y_test, prediction1.round()))

              precision    recall  f1-score   support

           0       0.59      0.67      0.62        15
           1       0.12      0.20      0.15         5
           2       0.00      0.00      0.00         4
           3       0.00      0.00      0.00         5
           4       0.00      0.00      0.00         2

   micro avg       0.35      0.35      0.35        31
   macro avg       0.14      0.17      0.16        31
weighted avg       0.30      0.35      0.33        31



/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [27]:
print (classification_report(y_test, prediction2.round()))

              precision    recall  f1-score   support

           0       0.70      0.47      0.56        15
           1       0.29      0.80      0.42         5
           2       0.40      0.50      0.44         4
           3       0.00      0.00      0.00         5
           4       0.00      0.00      0.00         2

   micro avg       0.42      0.42      0.42        31
   macro avg       0.28      0.35      0.29        31
weighted avg       0.44      0.42      0.40        31



In [28]:
print (classification_report(y_test, prediction3.round()))

              precision    recall  f1-score   support

           0       0.88      0.47      0.61        15
           1       0.19      0.60      0.29         5
           2       0.17      0.25      0.20         4
           3       0.00      0.00      0.00         5
           4       0.00      0.00      0.00         2

   micro avg       0.35      0.35      0.35        31
   macro avg       0.25      0.26      0.22        31
weighted avg       0.48      0.35      0.37        31



In [29]:
print (classification_report(y_test, prediction4.round()))

              precision    recall  f1-score   support

           0       0.82      0.60      0.69        15
           1       0.20      0.60      0.30         5
           2       0.20      0.25      0.22         4
           3       0.00      0.00      0.00         5
           4       0.00      0.00      0.00         2

   micro avg       0.42      0.42      0.42        31
   macro avg       0.24      0.29      0.24        31
weighted avg       0.45      0.42      0.41        31



In [30]:
print (classification_report(y_test, prediction5.round()))

              precision    recall  f1-score   support

           0       0.83      0.67      0.74        15
           1       0.25      0.60      0.35         5
           2       0.43      0.75      0.55         4
           3       0.00      0.00      0.00         5
           4       0.00      0.00      0.00         2

   micro avg       0.52      0.52      0.52        31
   macro avg       0.30      0.40      0.33        31
weighted avg       0.50      0.52      0.49        31

